package: simple_oauth
version: '1.0'

page:
    title: 'translate:simple_oauth'
    perm: simple_oauth[]
    subpages:
        settings: { title: 'translate:settings' }
        client:
            title: 'translate:simple_oauth_client'
            icon: rex-icon fa-user
        authcode:
            title: 'translate:simple_oauth_authcode'
            icon: rex-icon rex-icon-module
        token:
            title: 'translate:simple_oauth_token'
            icon: rex-icon rex-icon-module
        docs:
            title: 'Hilfe'
            pjax: false
            itemclass: pull-right
            subpages:
                intro:
                    title: 'translate:simple_oauth_docs_intro'
                    pjax: false
                    subPath: docs/intro.md

requires:
    packages:
        yform: '>=4.0-dev,<5.0.0-dev'
